server:
  port: 8090
---
spring:
  cloud:
    gateway:
      routes:
        - id: persons
          uri: http://localhost:8081/
          predicates:
            - Path=/persons/**
          filters:
            - AddResponseHeader=X-Response-Red, Blue
        - id: banksupdate
          uri: http://localhost:8083/
          predicates:
            - Path=/banks/**
          filters:
            - RewritePath=/banks/getBanks,/banksv1/getBanks
            - AddRequestHeader=Ree, Green
            - AddResponseHeader=X-Response-Red, White